name: Deploy to DigitalOcean

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Start SSH agent and add SSH key
      run: |
        mkdir -p ~/.ssh  # .ssh dizinini oluştur
        eval "$(ssh-agent -s)"
        echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add server to known hosts
      run: ssh-keyscan -H ${{ env.HOST }} >> ~/.ssh/known_hosts
      env:
        HOST: "167.71.54.125"

    - name: Deploy to DigitalOcean Server
      run: |
        scp -r * $USER@$HOST:/root/devops
        ssh $USER@$HOST << 'EOF'
          cd /root/devops
          npm install
          pm2 restart devops
        EOF
      env:
        HOST: "167.71.54.125"
        USER: "deployuser"
